#!/usr/bin/env node
import { mkdir, readFile, statSync, writeFile } from 'node:fs';
import prog from 'caporal';
import * as lnSync from 'ln-sync';

import { getAccountingReport } from './balances/get_accounting_report.js';
import { getDetailedBalance } from './balances/get_detailed_balance.js';
import { getBalance } from './balances/get_balance.js';
import { getLiquidity } from './balances/get_liquidity.js';
import { getUtxos } from './chain/get_utxos.js';
import { getChainFees } from './chain/get_chain_fees.js';
import { simpleRequest } from './commands/simple_request.js';
import { interrogate } from './commands/interrogate.js';
import { fetchRequest } from './commands/fetch_request.js';
import { authenticatedLnd } from './lnd/authenticated_lnd.js';
import { getLnds } from './lnd/get_lnds.js';
import { getCertValidityDays } from './lnd/get_cert_validity_days.js';
import { returnObject } from './responses/return_object.js';
import { returnNumber } from './responses/return_number.js';
import { returnOutput } from './responses/return_output.js';
import { returnChart } from './responses/return_chart.js';
import { getChainFeesChart } from './routing/get_chain_fees_chart.js';
import { getFeesChart } from './routing/get_fees_chart.js';
import { getFeesPaid } from './routing/get_fees_paid.js';
import { connectToRocketChat } from './rocketchat/connect_to_rocketchat.js';
import { manageTriggers } from './triggers/manage_triggers.js';
import { getReceivedChart } from './wallets/get_received_chart.js';
import { getReport } from './wallets/get_report.js';
import { getPeers } from './network/get_peers.js'
import { getForwards } from './network/get_forwards.js'
import { getGraphEntry } from './network/get_graph_entry.js'

import PACKAGE_JSON from './package.json' with { type: 'json' };
import commandConstants from './commands/constants.json' with { type: 'json' };

const {version} = PACKAGE_JSON;
const { accountingCategories, peerSortOptions } = commandConstants;

const collect = arr => [].concat(...[arr]).filter(n => !!n);
const {exit} = process;
const flatten = arr => [].concat(...arr);
const {INT} = prog;
const {keys} = Object;
const lndForNode = (node) => authenticatedLnd({node});
const months = [...Array(12).keys()].map(n => ++n);
const {REPEATABLE} = prog;
const {STRING} = prog;
const yearMatch = /^\d{4}$/;

prog
  .version(version)

  // Get accounting information
  .command('accounting', 'Get an accounting rundown')
  .argument('<category>', 'Report category', keys(accountingCategories))
  .help(`Categories: ${keys(accountingCategories).join(', ')}`)
  .help('Privacy note: this requests tx related data from third parties')
  .option('--csv', 'Output a CSV')
  .option('--date <day>', 'Show only records for specific date')
  .option('--disable-fiat', 'Avoid looking up fiat conversions for records')
  .option('--month <month>', 'Show only records for specific month', months)
  .option('--node <node_name>', 'Get details from named node')
  .option('--year <year>', 'Show only records for specified year', yearMatch)
  .action((args, options) => {
    const table = !!options.csv ? null : 'rows';

    return new Promise(async (resolve, reject) => {
      try {
        return getAccountingReport({
          category: args.category,
          date: options.date,
          is_csv: !!options.csv,
          is_fiat_disabled: options.disableFiat,
          lnd: (await authenticatedLnd({node: options.node})).lnd,
          month: options.month,
          node: options.node,
          request: simpleRequest,
          year: options.year,
        },
        returnObject({reject, resolve, table}));
      } catch (err) {
        console.error({err}) && reject();
      }
    });
  })

  // Get local balance information
  .command('balance', 'Get total tokens')
  .help('Sums balances on-chain, in channels, and pending, plus commit fees')
  .help('Multiple --node arguments are supported to sum across nodes')
  .option('--above <tokens>', 'Return tokens above watermark', INT)
  .option('--below <tokens>', 'Return tokens below watermark', INT)
  .option('--confirmed', 'Return confirmed funds only')
  .option('--detailed', 'Return detailed balance information')
  .option('--node <node_name>', 'Node to get balance for', REPEATABLE)
  .option('--offchain', 'List only off-chain tokens')
  .option('--onchain', 'List only on-chain tokens')
  .action((args, options) => {
    return new Promise(async (resolve, reject) => {
      try {
        // Exit early when detailed balance details are requested
        if (!!options.detailed) {
          return getDetailedBalance({
            lnds: (await getLnds({nodes: options.node})).lnds,
            is_confirmed: options.confirmed,
          },
          returnObject({reject, resolve}));
        }

        return getBalance({
          above: options.above,
          below: options.below,
          is_confirmed: !!options.confirmed,
          is_offchain_only: !!options.offchain,
          is_onchain_only: !!options.onchain,
          lnd: (await lndForNode(options.node)).lnd,
        },
        returnNumber({reject, resolve, number: 'balance'}));
      } catch (err) {
        console.error({err}) && reject();
      }
    });
  })

  // Get the number of days until the RPC cert expires
  .command('cert-validity-days', 'Number of days until the cert is invalid')
  .option('--below <number_of_days>', 'Return number of days below mark', INT)
  .option('--node <node_name>', 'Node to check cert on')
  .action((args, options) => {
    return new Promise(async (resolve, reject) => {
      return getCertValidityDays({
        below: options.below,
        node: options.node,
      },
      returnNumber({reject, resolve, number: 'days'}));
    });
  })

  // Get the current chain fee rates
  .command('chainfees', 'Get the current chain fee estimates')
  .help('Lookup chain fee estimates at various confirm targets')
  .option('--blocks <depth>', 'Blocks confirm target depth to estimate to')
  .option('--file <path>', 'Write the output to a JSON file at desired path')
  .option('--no-color', 'Mute all colors')
  .option('--node <node_name>', 'Node to get chain fees view from')
  .action((args, options) => {
    return new Promise(async (resolve, reject) => {
      try {
        return getChainFees({
          blocks: options.blocks,
          lnd: (await authenticatedLnd({node: options.node})).lnd,
        },
        returnObject({
          reject,
          resolve,
          file: options.file,
          write: writeFile,
        }));
      } catch (err) {
        console.error({err}) && reject();
      }
    });
  })

  // Show a chart of chain fees paid
  .command('chart-chain-fees', 'Get a chart of chain fee expenses')
  .help('Show chart of mining fee expenditure over time')
  .help('Privacy note: this requests tx data from third parties')
  .option('--days <days>', 'Chart over the past number of days', INT)
  .option('--end <end_date>', 'End date for chart as YYYY-MM-DD', STRING)
  .option('--no-color', 'Disable colors')
  .option('--node <node_name>', 'Chain fees from saved node(s)', REPEATABLE)
  .option('--start <start_date>', 'Start date for chart as YYYY-MM-DD', STRING)
  .action((args, options) => {
    return new Promise(async (resolve, reject) => {
      try {
        return getChainFeesChart({
          days: options.days,
          end_date: options.end,
          is_monochrome: !!options.noColor,
          lnds: (await getLnds({nodes: options.node})).lnds,
          request: simpleRequest,
          start_date: options.start,
        },
        returnChart({reject, resolve, data: 'data'}));
      } catch (err) {
        console.error({err}) && reject();
      }
    });
  })

  // Show a chart of fees earned
  .command('chart-fees-earned', 'Get a chart of earned routing fees')
  .argument('[via]', 'Routing fees earned via a specified node or tag')
  .help('Show the routing fees earned')
  .option('--count', 'Show count of forwards instead of fees earned')
  .option('--days <days>', 'Chart fees over the past number of days', INT)
  .option('--end <end_date>', 'End date for chart as YYYY-MM-DD', STRING)
  .option('--forwarded', 'Show amount forwarded instead of fees earned')
  .option('--node <node_name>', 'Get saved node fees earned', REPEATABLE)
  .option('--start <start_date>', 'Start date for chart as YYYY-MM-DD', STRING)
  .action((args, options) => {
    return new Promise(async (resolve, reject) => {
      try {
        return getFeesChart({
          days: options.days,
          end_date: options.end,
          fs: {getFile: readFile},
          is_count: options.count,
          is_forwarded: options.forwarded,
          lnds: (await getLnds({nodes: options.node})).lnds,
          start_date: options.start,
          via: args.via || undefined,
        },
        returnChart({reject, resolve, data: 'data'}));
      } catch (err) {
        console.error({err}) && reject();
      }
    });
  })

  // Show a chart of routing fees paid
  .command('chart-fees-paid', 'Get a chart of paid routing fees')
  .help('Show the routing fees paid to forwarding nodes')
  .help('--rebalances can return results much more quickly')
  .option('--days <days>', 'Chart fees over the past number of days', INT)
  .option('--end <end_date>', 'End date for chart as YYYY-MM-DD', STRING)
  .option('--in <key_or_alias>', 'Fees paid on routes in node with peer')
  .option('--most-fees', 'View table of fees paid per node')
  .option('--most-forwarded', 'View table of forwarded per node')
  .option('--network', 'Show only non-peers in table view')
  .option('--node <node_name>', 'Get fees chart for saved node(s)', REPEATABLE)
  .option('--out <key_or_alias>', 'Fees paid on routes out node with peer')
  .option('--peers', 'Show only peers in table view')
  .option('--rebalances', 'Only consider fees paid in self-to-self transfers')
  .option('--start <start_date>', 'Start date for chart as YYYY-MM-DD', STRING)
  .action((args, options) => {
    return new Promise(async (resolve, reject) => {
      const data = 'data';
      const table = 'rows';

      const asTable = returnObject({reject, resolve, table});
      const chart = returnChart({data, reject, resolve});

      try {
        return getFeesPaid({
          days: options.days,
          end_date: options.end,
          fs: {getFile: readFile},
          in: options.in,
          is_most_fees_table: options.mostFees,
          is_most_forwarded_table: options.mostForwarded,
          is_network: options.network,
          is_peer: options.peers,
          is_rebalances_only: options.rebalances,
          lnds: (await getLnds({nodes: options.node})).lnds,
          out: options.out,
          start_date: options.start,
        },
        (options.mostFees || options.mostForwarded) ? asTable : chart);
      } catch (err) {
        console.error({err}) && reject();
      }
    });
  })

  // Chart earnings from payments received
  .command('chart-payments-received', 'Get a chart of received payments')
  .help('Show chart for settled invoices from external parties')
  .option('--count', 'Show count of settled instead of amount received')
  .option('--days <days>', 'Chart over the past number of days', INT)
  .option('--end <end_date>', 'Final date for chart as YYYY-MM-DD', STRING)
  .option('--for <query>', 'Only consider payments including a specific query')
  .option('--node <node_name>', 'Get payments from saved node(s)', REPEATABLE)
  .option('--start <start_date>', 'Start date for chart as YYYY-MM-DD', STRING)
  .action((args, options) => {
    return new Promise(async (resolve, reject) => {
      try {
        return getReceivedChart({
          days: options.days,
          end_date: options.end,
          is_count: options.count,
          lnds: (await getLnds({nodes: options.node})).lnds,
          query: options.for,
          start_date: options.start,
        },
        returnChart({reject, resolve, data: 'data'}));
      } catch (err) {
        console.error({err}) && reject();
      }
    });
  })

  // Get forwards
  .command('forwards', 'Show recent forwarding earnings')
  .help('Peers where routing has taken place from inbound and outbound sides')
  .help('Sorts: earned_in/earned_out/earned_total/inbound/liquidity/outbound')
  .option('--complete', 'Show complete set of records in non table view')
  .option('--days <days>', 'Number of past days to evaluate', INT)
  .option('--in <from>', 'Forwards that originated from a specific peer')
  .option('--no-color', 'Mute all colors')
  .option('--node <node_name>', 'Node to get forwards for')
  .option('--out <to>', 'Forwards that sent out to a specified peer')
  .option('--sort <type>', 'Sort forward-active peers by earnings/liquidity')
  .option('--tag <tag_name>', 'Only show peers in a tag', REPEATABLE)
  .action((args, options) => {
    return new Promise(async (resolve, reject) => {
      try {
        const {lnd} = await lndForNode(options.node);
        const table = !!options.complete ? undefined : 'rows';

        return getForwards({
          lnd,
          days: options.days,
          from: (await lnSync.findKey({lnd, query: options.in})).public_key,
          fs: {getFile: readFile},
          is_monochrome: !!options.noColor,
          is_table: !options.complete,
          sort: options.sort || undefined,
          tags: collect(options.tag),
          to: (await lnSync.findKey({lnd, query: options.out})).public_key,
        },
        returnObject({reject, resolve, table}));
      } catch (err) {
        console.error({err}) && reject();
      }
    });
  })

  // Get the edges of a given node
  .command('graph', 'List out the connections a node has with other nodes')
  .argument('<alias_or_public_key>', 'Node in the graph to look up')
  .help('--filter variables: AGE/CAPACITY/HOPS/IN_FEE_RATE/OUT_FEE_RATE')
  .help('Example: --filter "age<7*144" for connections in the last week')
  .help(' ←-PPM will represent a source-based inbound discount when present')
  .option('--filter <formula>', 'Filter formula to apply', REPEATABLE)
  .option('--node <node_name>', 'Node to use for lookup')
  .option('--sort <sort_connections_by', 'Sort peers by field')
  .action((args, options) => {
    return new Promise(async (resolve, reject) => {
      try {
        const {lnd} = await lndForNode(options.node);

        return getGraphEntry({
          lnd,
          filters: flatten([options.filter].filter(n => !!n)),
          fs: {getFile: readFile},
          query: args.aliasOrPublicKey.trim(),
          sort: options.sort,
        },
        returnObject({reject, resolve, table: 'rows'}));
      } catch (err) {
        console.error({err}) && reject();
      }
    });
  })

  // Get inbound liquidity information: available inbound off-chain tokens
  .command('inbound-liquidity', 'Get inbound liquidity size')
  .option('--above <tokens>', 'Return amount above watermark', INT)
  .option('--below <tokens>', 'Return amount above watermark', INT)
  .option('--max-fee-rate <fee_rate>', 'Maximum fee rate to consider', INT)
  .option('--node <node_name>', 'Node to get inbound liquidity')
  .option('--top', 'Top percentile inbound liquidity in an individual channel')
  .option('--with <node_key_or_tag>', 'Liquidity with a specific node/tag')
  .action((args, options) => {
    return new Promise(async (resolve, reject) => {
      try {
        return getLiquidity({
          above: options.above || undefined,
          below: options.below || undefined,
          fs: {getFile: readFile},
          is_top: options.top || undefined,
          lnd: (await authenticatedLnd({node: options.node})).lnd,
          max_fee_rate: options.maxFeeRate || undefined,
          request: simpleRequest,
          with: options.with,
        },
        returnNumber({reject, resolve, number: 'balance'}));
      } catch (err) {
        console.error({err}) && reject();
      }
    });
  })

  // Get outbound liquidity information: available outbound off-chain tokens
  .command('outbound-liquidity', 'Get outbound liquidity size')
  .option('--above <tokens>', 'Return amount above watermark', INT)
  .option('--below <tokens>', 'Return amount above watermark', INT)
  .option('--node <node_name>', 'Node to get outbound liquidity amount')
  .option('--top', 'Top percentile inbound liquidity in an individual channel')
  .option('--with <public_key_or_tag>', 'Liquidity with a specific node/tag')
  .action((args, options) => {
    return new Promise(async (resolve, reject) => {
      try {
        return getLiquidity({
          above: options.above || undefined,
          below: options.below || undefined,
          fs: {getFile: readFile},
          is_outbound: true,
          is_top: options.top || undefined,
          lnd: (await authenticatedLnd({node: options.node})).lnd,
          with: options.with,
        },
        returnNumber({reject, resolve, number: 'balance'}));
      } catch (err) {
        console.error({err}) && reject();
      }
    });
  })

  // Get a list of channel-connected peers
  .command('peers', 'Get a list of channel-connected peers')
  .help(`Sort options: ${peerSortOptions.join(', ')}`)
  .help('Icons: 🤢 often d/c, 💸 active HTLC, 💀 d/c, 🌚 private')
  .help('Icons: 🧊 delayed coop close, ⏳ pending channel, 🚫 in disabled')
  .help('Icons: 🦐 limited max htlc')
  .help('Filters can take formula expressions to limit results')
  .help('Filter variable AGE: "age > 144 * 7" for peers older than a week')
  .help('Filter variable BLOCKS_SINCE_LAST_CHANNEL: blocks since recent open')
  .help('Filter variable CAPACITY: "capacity > 8*m"')
  .help('Filter variable DISK_USAGE_MB: "disk_usage_mb > 9" for disk estimate')
  .help('Filter variable INBOUND_LIQUIDITY: "inbound_liquidity > 1*m"')
  .help('Filter variable OUTBOUND_LIQUIDITY: "outbound_liquidity > 1*m"')
  .option('--active', 'Only active peer channels')
  .option('--complete', 'Show complete set of records in non table view')
  .option('--fee-days <past_days>', 'Include fees earned over n days', INT)
  .option('--filter <formula>', 'Filter formula to apply', REPEATABLE)
  .option('--idle-days <days>', 'No receives or routes for n days', INT)
  .option('--no-color', 'Mute all colors')
  .option('--node <node_name>', 'Node to get peers for')
  .option('--offline', 'Only offline peer channels')
  .option('--omit <key>', 'Omit peer with public key', REPEATABLE)
  .option('--private', 'Only private channels')
  .option('--public', 'Only peers with public channels')
  .option('--sort <by>', 'Sort results by peer attribute', peerSortOptions)
  .option('--tag <tag_name>', 'Only show peers in a tag', REPEATABLE)
  .action((args, options) => {
    const table = !!options.complete ? undefined : 'rows';

    return new Promise(async (resolve, reject) => {
      try {
        return getPeers({
          earnings_days: options.feeDays,
          filters: flatten([options.filter].filter(n => !!n)),
          fs: {getFile: readFile},
          idle_days: options.idleDays || undefined,
          is_active: !!options.active,
          is_monochrome: !!options.noColor,
          is_offline: !!options.offline,
          is_private: !!options.private,
          is_public: !!options.public,
          is_table: !options.complete,
          lnd: (await authenticatedLnd({node: options.node})).lnd,
          omit: flatten([options.omit].filter(n => !!n)),
          sort_by: options.sort,
          tags: flatten([options.tag].filter(n => !!n)),
        },
        returnObject({reject, resolve, table}));
      } catch (err) {
        console.error({err}) && reject();
      }
    });
  })

  // See a general report about the node
  .command('report', 'Report about the node')
  .option('--node <node_name>', 'Node to get report for')
  .option('--styled', 'Add unicode styling to report')
  .action((args, options) => {
    return new Promise((resolve, reject) => {
      return getReport({
        fs: {getFile: readFile},
        node: options.node,
        request: simpleRequest,
        style: !!options.styled ? 'styled' : undefined,
      },
      returnOutput({reject, resolve}));
    });
  })

  // Link up RocketChat bot
  .command('rocketchat', 'Post updates to a RocketChat bot')
  .help('Connect to a RocketChat bot. Create bot in RocketChat')
  .help('Supported updates: forwards, received payments, etc')
  .help('Multiple nodes are supported by repeating the `--node` flag')
  .help('See README for info on persisting the bot through nohup')
  .option('--budget <amount>', 'Spending amount to allow', INT, Number())
  .option('--connect <connect_code>', 'Connection code from /connect')
  .option('--ignore-forwards-below <amount>', 'Ignore forwards of value', INT)
  .option('--ignore-rebalances-below <amt>', 'Ignore rebalances of value', INT)
  .option('--node <node_name>', 'Node to connect to RocketChat', REPEATABLE)
  .option('--reset-api-key', 'Reset the RocketChat API key')
  .option('--use-rounded-units', 'No leading zeros or fractions on amounts')
  .option('--use-small-units', 'Avoid showing leading zeros on amounts')
  .action((args, options) => {
    return new Promise(async (resolve, reject) => {
      try {
        return await connectToRocketChat({
          fs: {
            writeFile,
            getFile: readFile,
            getFileStatus: statSync,
            is_reset_state: options.resetApiKey || undefined,
            makeDirectory: mkdir,
          },
          id: options.connect,
          is_rounded_units: options.useRoundedUnits || undefined,
          is_small_units: options.useSmallUnits || undefined,
          min_forward_tokens: options.ignoreForwardsBelow || undefined,
          min_rebalance_tokens: options.ignoreRebalancesBelow || undefined,
          nodes: flatten([options.node].filter(n => !!n)),
          request: fetchRequest({fetch}),
        });
      } catch (err) {
        console.error({err}) && reject();
      }
    });
  })

  // Manage triggers
  .command('triggers', 'Manage event triggers')
  .option('--node <name>', 'Node to manage triggers on')
  .visible(false)
  .action((args, options) => {
    return new Promise(async (resolve, reject) => {
      try {
        return manageTriggers({
          ask: await interrogate({}),
          lnd: (await lndForNode(options.node)).lnd,
        },
        returnObject({exit, reject, resolve}));
      } catch (err) {
        console.error({err}) && reject();
      }
    });
  })

  // Get utxos
  .command('utxos', 'Get a list of utxos')
  .option('--confirmed', 'Return only confirmed utxos')
  .option('--count', 'Return the count of utxos')
  .option('--count-below <below>', 'Return only count below number', INT)
  .option('--no-color', 'Mute all colors')
  .option('--node <node_name>', 'Node to get utxos for')
  .option('--size', 'UTXOs of size greater than or equal to specified amount')
  .action((args, options) => {
    return new Promise(async (resolve, reject) => {
      try {
        return getUtxos({
          count_below: options.countBelow,
          is_confirmed: !!options.confirmed,
          is_count: !!options.count,
          lnd: (await authenticatedLnd({node: options.node})).lnd,
          min_tokens: options.size || undefined,
          node: options.node,
        },
        returnObject({reject, resolve}));
      } catch (err) {
        console.error({err}) && reject();
      }
    });
  });

prog.parse(process.argv);
