packages:
  - 'packages/*'

linkWorkspacePackages: true
sharedWorkspaceLockfile: true

minimumReleaseAgeExclude:
- oxlint
- "@oxlint/binding-linux-x64-gnu"
- inquirer
- "@inquirer/core"
- "@types/node"
- bn.js
- psbt
