packages:
  - 'packages/asyncjs-util'
  - 'packages/bolt01'
  - 'packages/bolt07'
  - 'packages/bolt09'
  - 'packages/caporal'
  - 'packages/fiat'
  - 'packages/invoices'
  - 'packages/lightning'
  - 'packages/ln-accounting'
  - 'packages/ln-docker-daemons'
  - 'packages/ln-rocketchat'
  - 'packages/ln-service'
  - 'packages/ln-sync'
  - 'packages/mock-lnd'

linkWorkspacePackages: true
sharedWorkspaceLockfile: true

minimumReleaseAgeExclude:
- oxlint
- "@oxlint/binding-linux-x64-gnu"
- inquirer
- "@inquirer/core"
- "@types/node"
- bn.js
- psbt
